# Generated by Django 4.2 on 2026-03-30 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import progress.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_number', models.CharField(default=progress.models.generate_certificate_id, help_text='Sertifikatning unikal seriya raqami', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Masalan: Medical English Fundamentals', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Sertifikat nima uchun berilganligi haqida')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qrcodes/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-issued_at'],
            },
        ),
    ]
