# Generated by Django 4.2 on 2026-03-27 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField()),
                ('corrected_text', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grammar Check',
                'verbose_name_plural': 'Grammar Checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
