# Generated by Django 4.2 on 2026-03-27 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('tests_taken', models.PositiveIntegerField(default=0)),
                ('simulations_started', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Statistic',
                'verbose_name_plural': 'Daily Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('test', 'Test'), ('grammar', 'Grammar Check'), ('simulation', 'Simulation'), ('chat', 'Chat')], max_length=20)),
                ('action', models.CharField(choices=[('view', 'View/Open'), ('start', 'Start'), ('complete', 'Complete'), ('submit', 'Submit')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Metadata for the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
