# Generated by Django 4.2 on 2026-03-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, help_text="Yordamchi ma'lumot (Hint).", max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('matching', 'Terminology Matching'), ('gap_fill', 'Text Completion (Gap Fill)'), ('true_false', 'True / False')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='rationale',
            field=models.TextField(blank=True, help_text="To'g'ri javob uchun qisqacha izoh (English)."),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Savol matni yoki kontekst matni (gap fill uchun).'),
        ),
    ]
